apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: clusterregistry
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  type: LoadBalancer
  selector:
    apiserver: "true"
