// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	registry "k8s.io/kubernetes/federation/clusterregistry/pkg/apis/registry"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_AuthInfo_To_registry_AuthInfo,
		Convert_registry_AuthInfo_To_v1alpha1_AuthInfo,
		Convert_v1alpha1_CloudProvider_To_registry_CloudProvider,
		Convert_registry_CloudProvider_To_v1alpha1_CloudProvider,
		Convert_v1alpha1_Cluster_To_registry_Cluster,
		Convert_registry_Cluster_To_v1alpha1_Cluster,
		Convert_v1alpha1_ClusterList_To_registry_ClusterList,
		Convert_registry_ClusterList_To_v1alpha1_ClusterList,
		Convert_v1alpha1_KubeAPIServer_To_registry_KubeAPIServer,
		Convert_registry_KubeAPIServer_To_v1alpha1_KubeAPIServer,
	)
}

func autoConvert_v1alpha1_AuthInfo_To_registry_AuthInfo(in *AuthInfo, out *registry.AuthInfo, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_AuthInfo_To_registry_AuthInfo is an autogenerated conversion function.
func Convert_v1alpha1_AuthInfo_To_registry_AuthInfo(in *AuthInfo, out *registry.AuthInfo, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthInfo_To_registry_AuthInfo(in, out, s)
}

func autoConvert_registry_AuthInfo_To_v1alpha1_AuthInfo(in *registry.AuthInfo, out *AuthInfo, s conversion.Scope) error {
	return nil
}

// Convert_registry_AuthInfo_To_v1alpha1_AuthInfo is an autogenerated conversion function.
func Convert_registry_AuthInfo_To_v1alpha1_AuthInfo(in *registry.AuthInfo, out *AuthInfo, s conversion.Scope) error {
	return autoConvert_registry_AuthInfo_To_v1alpha1_AuthInfo(in, out, s)
}

func autoConvert_v1alpha1_CloudProvider_To_registry_CloudProvider(in *CloudProvider, out *registry.CloudProvider, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_CloudProvider_To_registry_CloudProvider is an autogenerated conversion function.
func Convert_v1alpha1_CloudProvider_To_registry_CloudProvider(in *CloudProvider, out *registry.CloudProvider, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudProvider_To_registry_CloudProvider(in, out, s)
}

func autoConvert_registry_CloudProvider_To_v1alpha1_CloudProvider(in *registry.CloudProvider, out *CloudProvider, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_registry_CloudProvider_To_v1alpha1_CloudProvider is an autogenerated conversion function.
func Convert_registry_CloudProvider_To_v1alpha1_CloudProvider(in *registry.CloudProvider, out *CloudProvider, s conversion.Scope) error {
	return autoConvert_registry_CloudProvider_To_v1alpha1_CloudProvider(in, out, s)
}

func autoConvert_v1alpha1_Cluster_To_registry_Cluster(in *Cluster, out *registry.Cluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_KubeAPIServer_To_registry_KubeAPIServer(&in.KubeAPIServer, &out.KubeAPIServer, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_AuthInfo_To_registry_AuthInfo(&in.AuthInfo, &out.AuthInfo, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CloudProvider_To_registry_CloudProvider(&in.CloudProvider, &out.CloudProvider, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Cluster_To_registry_Cluster is an autogenerated conversion function.
func Convert_v1alpha1_Cluster_To_registry_Cluster(in *Cluster, out *registry.Cluster, s conversion.Scope) error {
	return autoConvert_v1alpha1_Cluster_To_registry_Cluster(in, out, s)
}

func autoConvert_registry_Cluster_To_v1alpha1_Cluster(in *registry.Cluster, out *Cluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_registry_KubeAPIServer_To_v1alpha1_KubeAPIServer(&in.KubeAPIServer, &out.KubeAPIServer, s); err != nil {
		return err
	}
	if err := Convert_registry_AuthInfo_To_v1alpha1_AuthInfo(&in.AuthInfo, &out.AuthInfo, s); err != nil {
		return err
	}
	if err := Convert_registry_CloudProvider_To_v1alpha1_CloudProvider(&in.CloudProvider, &out.CloudProvider, s); err != nil {
		return err
	}
	return nil
}

// Convert_registry_Cluster_To_v1alpha1_Cluster is an autogenerated conversion function.
func Convert_registry_Cluster_To_v1alpha1_Cluster(in *registry.Cluster, out *Cluster, s conversion.Scope) error {
	return autoConvert_registry_Cluster_To_v1alpha1_Cluster(in, out, s)
}

func autoConvert_v1alpha1_ClusterList_To_registry_ClusterList(in *ClusterList, out *registry.ClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]registry.Cluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ClusterList_To_registry_ClusterList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterList_To_registry_ClusterList(in *ClusterList, out *registry.ClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterList_To_registry_ClusterList(in, out, s)
}

func autoConvert_registry_ClusterList_To_v1alpha1_ClusterList(in *registry.ClusterList, out *ClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items == nil {
		out.Items = make([]Cluster, 0)
	} else {
		out.Items = *(*[]Cluster)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_registry_ClusterList_To_v1alpha1_ClusterList is an autogenerated conversion function.
func Convert_registry_ClusterList_To_v1alpha1_ClusterList(in *registry.ClusterList, out *ClusterList, s conversion.Scope) error {
	return autoConvert_registry_ClusterList_To_v1alpha1_ClusterList(in, out, s)
}

func autoConvert_v1alpha1_KubeAPIServer_To_registry_KubeAPIServer(in *KubeAPIServer, out *registry.KubeAPIServer, s conversion.Scope) error {
	out.Server = registry.URL(in.Server)
	return nil
}

// Convert_v1alpha1_KubeAPIServer_To_registry_KubeAPIServer is an autogenerated conversion function.
func Convert_v1alpha1_KubeAPIServer_To_registry_KubeAPIServer(in *KubeAPIServer, out *registry.KubeAPIServer, s conversion.Scope) error {
	return autoConvert_v1alpha1_KubeAPIServer_To_registry_KubeAPIServer(in, out, s)
}

func autoConvert_registry_KubeAPIServer_To_v1alpha1_KubeAPIServer(in *registry.KubeAPIServer, out *KubeAPIServer, s conversion.Scope) error {
	out.Server = URL(in.Server)
	return nil
}

// Convert_registry_KubeAPIServer_To_v1alpha1_KubeAPIServer is an autogenerated conversion function.
func Convert_registry_KubeAPIServer_To_v1alpha1_KubeAPIServer(in *registry.KubeAPIServer, out *KubeAPIServer, s conversion.Scope) error {
	return autoConvert_registry_KubeAPIServer_To_v1alpha1_KubeAPIServer(in, out, s)
}
